version: '3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./app:/app
    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        working_dir: /app    
        volumes:
            - ./app:/app
    mysql:
        image: mariadb:latest
        environment:
            MYSQL_ROOT_PASSWORD: room123
            MYSQL_USER: room
            MYSQL_PASSWORD: room123
            MYSQL_DATABASE: developmentdb
        volumes:
            - mysqldata:/var/lib/mysql
            - ./sql:/docker-entrypoint-initdb.d
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        environment:
            PMA_HOST: mysql
            PMA_USER: root
            PMA_PASSWORD: secret123
        ports:
            - 8080:80

volumes:
    mysqldata: {}